[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Service-Worker-Allowed = "/"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[build]
  publish = "dist"
  command = "npm run build"

[dev]
  framework = "#static"
  targetPort = 3000
  autoLaunch = true
